import type { Metadata } from 'next';
import { cn } from '@/lib/utils';
import localFont from 'next/font/local';
import { Bebas_Neue, Margarine } from 'next/font/google';
import './globals.css';
import Header from './components/header';

const gokil = localFont({
  src: './Gokil.woff2',
  display: 'swap',
  variable: '--font-gokil',
});

const margarine = Margarine({
  subsets: ['latin'],
  weight: '400',
  display: 'swap',
  variable: '--font-margarine',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(gokil.variable, margarine.className)}>
        {/* <Header /> */}
        {children}
      </body>
    </html>
  );
}
